"""ADR-037/ADR-022 amendment (2026-09-05): the confirmation-side
counterpart to `shape_a_batch_manifest.py` -- an immutable,
human-reviewable batch manifest binding N Shape-A pending confirmation
requests to one owner approval, so a batch of confirmations needs
exactly one literal owner `yes` instead of one per capability.

## Why a separate module instead of reusing `ShapeABatchManifest`

Authorization previews share one `requested_plan_digest`/`requested_step_id`
across an entire homogeneous batch -- that shared digest is what makes
"one posture check governs the whole batch" a meaningful invariant.
Pending confirmation requests have no equivalent shared digest: each one
is intrinsically bound to its own, already-created `RecoveryContract`
(`contract_id`/`operation_id`), and its own `intent_digest` -- these are
never expected to match across capabilities, even within one homogeneous
batch. Reusing `ShapeABatchManifest`'s homogeneity predicate (same
`requested_plan_digest`, etc.) would therefore either be meaningless for
confirmations or would have to be silently bypassed, which is worse than
a separate, honestly-scoped type. This module's own homogeneity
predicate is instead exactly the two facts that ARE expected to be
shared across a batch confirmed by the same signer sitting: the pinned
`expected_authority_id` and `expected_algorithm` every pending request
already carries.

## What this module is, and is not

Same discipline as `ShapeABatchManifest`: a **derived, read-only view**
over already-integrity-verified `ShapeAPendingConfirmationRequest`
artifacts -- never a new source of truth, never itself signed. Its
entries carry each capability's already-existing `contract_id`/
`operation_id`/`intent_digest` -- values that exist on disk BEFORE this
manifest is ever built (they come from an already-created
`RecoveryContract`, never generated by this module or by the signer) --
so, unlike authorization's `authorization_id`, there is nothing to
pre-generate here; the batch-owner-approval module that consumes this
manifest (`shape_a_confirmation_batch_owner_approval.py`) commits
directly to these pre-existing identifiers.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

from .canonical import CanonicalValue, canonical_json
from .errors import Tier1Error
from .shape_a_artifact_exchange import ShapeAPendingConfirmationRequest

SHAPE_A_CONFIRMATION_BATCH_MANIFEST_SCHEMA_VERSION = 1

#: Domain-separation literal -- see `shape_a_batch_manifest.py`'s own
#: `_MANIFEST_DIGEST_DOMAIN` for the identical rationale.
_MANIFEST_DIGEST_DOMAIN = b"pfsense-mcp-shape-a-confirmation-batch-manifest-v1\0"

_MAX_BATCH_SIZE = 200


class ShapeAConfirmationBatchManifestError(Tier1Error):
    """Refused: empty batch, duplicate capability, or a batch whose
    pending requests do not share one homogeneous
    expected_authority_id/expected_algorithm."""


@dataclass(frozen=True)
class ShapeAConfirmationBatchManifestEntry:
    capability_symbol: str
    contract_id: str
    operation_id: str
    intent_digest: str
    semantic_fields: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class ShapeAConfirmationBatchManifest:
    schema_version: int
    batch_id: str
    capability_symbols: tuple[str, ...]
    entries: tuple[ShapeAConfirmationBatchManifestEntry, ...]
    expected_authority_id: str
    expected_algorithm: str


def build_shape_a_confirmation_batch_manifest(
    pending_requests: tuple[ShapeAPendingConfirmationRequest, ...], *, batch_id: str
) -> ShapeAConfirmationBatchManifest:
    """The one place a `ShapeAConfirmationBatchManifest` is constructed.
    `pending_requests` must already be individually integrity-verified
    by the caller (`load_shape_a_pending_confirmation_request()`,
    unchanged) -- this function never reads a file; it only validates
    cross-request consistency and canonicalizes ordering."""

    if not isinstance(pending_requests, tuple) or not pending_requests:
        raise ShapeAConfirmationBatchManifestError(
            "A confirmation batch manifest requires a non-empty, explicit tuple of pending requests."
        )
    if len(pending_requests) > _MAX_BATCH_SIZE:
        raise ShapeAConfirmationBatchManifestError(
            f"Batch size {len(pending_requests)} exceeds the maximum of {_MAX_BATCH_SIZE}."
        )
    if not all(isinstance(pending, ShapeAPendingConfirmationRequest) for pending in pending_requests):
        raise ShapeAConfirmationBatchManifestError(
            "Every batch entry must be an already-verified ShapeAPendingConfirmationRequest."
        )
    if not isinstance(batch_id, str) or not batch_id:
        raise ShapeAConfirmationBatchManifestError("batch_id must be a non-empty string.")

    symbols = [pending.capability_symbol for pending in pending_requests]
    if len(set(symbols)) != len(symbols):
        raise ShapeAConfirmationBatchManifestError(
            "Confirmation batch manifest must not contain duplicate capability_symbol entries."
        )

    first = pending_requests[0]
    for pending in pending_requests[1:]:
        if (
            pending.expected_authority_id != first.expected_authority_id
            or pending.expected_algorithm != first.expected_algorithm
        ):
            raise ShapeAConfirmationBatchManifestError(
                "Confirmation batch manifest requires every pending request to share the exact same "
                "expected_authority_id and expected_algorithm -- refusing a batch that would mix signing "
                "authorities or algorithms under one approval."
            )

    ordered = sorted(pending_requests, key=lambda pending: pending.capability_symbol)
    entries = tuple(
        ShapeAConfirmationBatchManifestEntry(
            capability_symbol=pending.capability_symbol,
            contract_id=pending.contract_id,
            operation_id=pending.operation_id,
            intent_digest=pending.intent_digest,
            semantic_fields=pending.semantic_fields,
        )
        for pending in ordered
    )
    return ShapeAConfirmationBatchManifest(
        schema_version=SHAPE_A_CONFIRMATION_BATCH_MANIFEST_SCHEMA_VERSION,
        batch_id=batch_id,
        capability_symbols=tuple(entry.capability_symbol for entry in entries),
        entries=entries,
        expected_authority_id=first.expected_authority_id,
        expected_algorithm=first.expected_algorithm,
    )


def _manifest_payload(manifest: ShapeAConfirmationBatchManifest) -> dict[str, CanonicalValue]:
    return {
        "schema_version": manifest.schema_version,
        "batch_id": manifest.batch_id,
        "capability_symbols": list(manifest.capability_symbols),
        "entries": [
            {
                "capability_symbol": entry.capability_symbol,
                "contract_id": entry.contract_id,
                "operation_id": entry.operation_id,
                "intent_digest": entry.intent_digest,
                "semantic_fields": [list(pair) for pair in entry.semantic_fields],
            }
            for entry in manifest.entries
        ],
        "expected_authority_id": manifest.expected_authority_id,
        "expected_algorithm": manifest.expected_algorithm,
    }


def compute_shape_a_confirmation_batch_manifest_digest(manifest: ShapeAConfirmationBatchManifest) -> str:
    if not isinstance(manifest, ShapeAConfirmationBatchManifest):
        raise ShapeAConfirmationBatchManifestError("Expected ShapeAConfirmationBatchManifest.")
    hasher = hashlib.sha256()
    hasher.update(_MANIFEST_DIGEST_DOMAIN)
    hasher.update(canonical_json(_manifest_payload(manifest)))
    return hasher.hexdigest()


def render_shape_a_confirmation_batch_manifest_review(manifest: ShapeAConfirmationBatchManifest) -> str:
    lines = [
        f"Batch confirmation review -- {len(manifest.entries)} capabilities, ONE owner approval",
        f"  batch_id:              {manifest.batch_id}",
        f"  manifest_digest:       {compute_shape_a_confirmation_batch_manifest_digest(manifest)}",
        f"  expected_authority_id: {manifest.expected_authority_id}",
        f"  expected_algorithm:    {manifest.expected_algorithm}",
        "",
        "Capabilities in this batch (canonical order):",
    ]
    for entry in manifest.entries:
        lines.append(f"  - {entry.capability_symbol}")
        lines.append(f"      contract_id:   {entry.contract_id}")
        lines.append(f"      operation_id:  {entry.operation_id}")
        lines.append(f"      intent_digest: {entry.intent_digest}")
        for name, value in entry.semantic_fields:
            lines.append(f"      {name} = {value}")
    lines.append("")
    lines.append(
        "Approving this batch authorizes confirming exactly these "
        f"{len(manifest.entries)} already-PREPARED contracts -- "
        "no other capability, no future addition, no substitution."
    )
    return "\n".join(lines)


__all__ = [
    "SHAPE_A_CONFIRMATION_BATCH_MANIFEST_SCHEMA_VERSION",
    "ShapeAConfirmationBatchManifest",
    "ShapeAConfirmationBatchManifestEntry",
    "ShapeAConfirmationBatchManifestError",
    "build_shape_a_confirmation_batch_manifest",
    "compute_shape_a_confirmation_batch_manifest_digest",
    "render_shape_a_confirmation_batch_manifest_review",
]
